### ISSUE TITLE
Explanation of Release Versions: Preview vs. Stable vs. Unstable

### ISSUE THREAD

**Issue by BRBsoup** [trindadedev13/Tiny-Installer#2]
The artifact APK's found on the Actions page are not really so clear... an explanation of all would be cool - maybe even of Debug vs. Release versions - at least saying what % each APK is working as expected and/or which features/advantagws/disadvantages each APK has compared to the others... Thanks!

**Comment by trindadedev13** [comment]
Hello @BRBBsoup, thank you very much for the suggestion, I will take a look at it, but honestly, I don't think there is any difference between stable, sample and unstable, but I will take a look, thanks.
